/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.librarymanagement;
import java.awt.GridLayout;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Suraj Upadhyay
 */
public class DeleteStudent extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form DeleteStudent
     */
    public DeleteStudent() {
        super("Delete Student");
        initComponents();
        try{
            Class.forName(LoginPage.DRIVER);
            conn=DriverManager.getConnection(LoginPage.JDBC_URL,"Root","root");
        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    int SearchStudent(){
        String ScholarNo=jtxtScholarNo.getText();
        String sql="SELECT * FROM STUDENT WHERE SCHOLARNO='"+ScholarNo+"'";
        try{
            rs=conn.prepareStatement(sql).executeQuery();
            if(rs.next()){ 
                return 1;
            }
            else return 0;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        return -1;
    }
    int SubmitBook(){
        String ScholarNo=jtxtScholarNo.getText();
        String sql="UPDATE BOOK SET SCHOLARNO=NULL ,FINE=NULL,ISSUDATE=NULL,SUBMITDATE=NULL"
                + " WHERE SCHOLARNO = '"+ScholarNo+"'";
        try{
            conn.prepareStatement(sql).executeUpdate();
            return 1;
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        return 0;
    }
    
    boolean Login(){
        String UserName,Password;
        String sql="SELECT * FROM ACCOUNT WHERE STATUS = TRUE";
        try{
            rs=conn.prepareStatement(sql).executeQuery();
            if(rs.next()){
                UserName=rs.getString("USERNAME");
                Password=rs.getString("PASSWORD");
                JTextField  Text0=new JTextField();
                JPasswordField Pswd0=new JPasswordField();
                JPanel Panel=new JPanel(new GridLayout(0,2));
                Panel.add(new JLabel("UserName : "));
                Text0.setText(UserName);
                Pswd0.setText("");
                Panel.add(Text0);
                Panel.add(new JLabel("Enter Password : "));
                Panel.add(Pswd0);
                int result=JOptionPane.showConfirmDialog(null,Panel,"Confirm it's you",JOptionPane.OK_CANCEL_OPTION);
                if(result==JOptionPane.OK_OPTION){
                    if(!String.valueOf(Pswd0.getPassword()).equals(Password)){
                        JOptionPane.showMessageDialog(null,"Wrong Password");
                        return false;
                    }
                    JOptionPane.showMessageDialog(null,"Are you SURE ?");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Wrong Password");
                    return false;
                }
                return true;
            }
            else{
                JOptionPane.showMessageDialog(null,"Cannot Access Account info");
                return false;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtScholarNo = new javax.swing.JTextField();
        jbtnDelete = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setTitle("Delete Student");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 0), 2, true), "Delete Student", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Scholar No :");

        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jtxtScholarNo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnDelete)
                .addGap(231, 231, 231))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtScholarNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        String ScholarNo=jtxtScholarNo.getText();
        int n=SearchStudent();
        if(n==0){JOptionPane.showMessageDialog(null,"Student is not in records");return ;}
        else if(n==-1) {JOptionPane.showMessageDialog(null,"Some error Occured");return ;}
        if(!Login()){return;}
        if(SubmitBook()==0){JOptionPane.showMessageDialog(null,"Some error Occured");return;}
        String sql="DELETE FROM STUDENT WHERE SCHOLARNO='"+ScholarNo+"'";
        try{
            conn.prepareStatement(sql).executeUpdate();
            JOptionPane.showMessageDialog(null,"Student erased from Records");
            rs.close();
            //pst.close();
            conn.close();
            this.setVisible(false);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
            String isbn;
            String sqlRecover="SELECT * FROM STUDENT WHERE SCHOLARNO='"+ScholarNo+"'";
            try{
                rs=conn.prepareStatement(sql).executeQuery();
                if(rs.next()){
                    isbn=rs.getString("ISBN");
                    sqlRecover="UPDATE BOOK SET SCHOLARNO = '"+ScholarNo+"' WHERE ISBN='"+isbn+"'";
                    conn.prepareStatement(sql).executeUpdate();
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JTextField jtxtScholarNo;
    // End of variables declaration//GEN-END:variables
}
