/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.librarymanagement;
import java.awt.GridLayout;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author Suraj Upadhyay
 */
public class Home extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form Home
     */
    public Home() {
        super("Home");
        initComponents();
    try {
        Class.forName(LoginPage.DRIVER);
        conn=DriverManager.getConnection(LoginPage.JDBC_URL,"Root","root");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }
    void clear(){
        jtxtScholarNo.setText("");
        jtxtISBN.setText("");
    }
    void Close(){
        try{
            rs.close();
            pst.close();
        }catch(Exception e){}
    }
    boolean checkMembership(){
        java.sql.Date Today=new java.sql.Date(new java.util.Date().getTime());
        java.sql.Date memEnd;
        String sql="SELECT * FROM STUDENT WHERE SCHOLARNO = '"+jtxtScholarNo.getText()+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            memEnd= new java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(rs.getString(7)).getTime());
            if(Today.after(memEnd)){
                Close();
                return false;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Close();
        return true;
    }
    boolean Issued(String ISBN){
        String sql="SELECT * FROM BOOK WHERE ISBN = '"+ISBN +"' AND SCHOLARNO IS NULL";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(!rs.next()){ Close();return true;}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        Close();
        return false;
    }
    /**
     * This method is called from within the constructor to initi alwaysalize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jtxtScholarNo = new javax.swing.JTextField();
        jbtnNewBook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnLogout = new javax.swing.JButton();
        jbtnSearchStudent = new javax.swing.JButton();
        jbtnIssueBook = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnSearchBook = new javax.swing.JButton();
        jbtnTransactionHistory = new javax.swing.JButton();
        jbtnNewStudent = new javax.swing.JButton();
        jtxtISBN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtnSubmit = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuSwitchUser = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuUpdateStudent = new javax.swing.JMenuItem();
        jMenuSearchStudent = new javax.swing.JMenuItem();
        jMenuDeleteStudent = new javax.swing.JMenuItem();
        jMenuListStudents = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuUpdateBook = new javax.swing.JMenuItem();
        jMenuSearchBook = new javax.swing.JMenuItem();
        jMenuDeleteBook = new javax.swing.JMenuItem();
        jMenuListBook = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuUserAccount = new javax.swing.JMenuItem();

        jMenu6.setText("File");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar1.add(jMenu7);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("File");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar4.add(jMenu10);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        jtxtScholarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtScholarNoActionPerformed(evt);
            }
        });

        jbtnNewBook.setText("New Book");
        jbtnNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewBookActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Book ISBN :");

        jbtnLogout.setText("Logout");
        jbtnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogoutActionPerformed(evt);
            }
        });

        jbtnSearchStudent.setText("Search Student");
        jbtnSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchStudentActionPerformed(evt);
            }
        });

        jbtnIssueBook.setText("Issue a Book");
        jbtnIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIssueBookActionPerformed(evt);
            }
        });

        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnSearchBook.setText("Search Book");
        jbtnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchBookActionPerformed(evt);
            }
        });

        jbtnTransactionHistory.setText("View Transaction History");
        jbtnTransactionHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTransactionHistoryActionPerformed(evt);
            }
        });

        jbtnNewStudent.setText("New Student");
        jbtnNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNewStudentActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Scholar No :");

        jbtnSubmit.setText("Submit");
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnTransactionHistory)
                        .addGap(99, 99, 99)
                        .addComponent(jbtnLogout))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtScholarNo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jbtnSearchStudent)
                                .addGap(34, 34, 34)
                                .addComponent(jbtnNewStudent)
                                .addGap(37, 37, 37)
                                .addComponent(jbtnIssueBook)))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jbtnSearchBook)
                        .addGap(56, 56, 56)
                        .addComponent(jbtnNewBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnSubmit)
                        .addGap(51, 51, 51)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtScholarNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSearchStudent)
                    .addComponent(jbtnNewStudent)
                    .addComponent(jbtnIssueBook))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSearchBook)
                    .addComponent(jbtnNewBook)
                    .addComponent(jbtnSubmit))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnTransactionHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu3.setText("         File       ");

        jMenuSwitchUser.setText("Switch User");
        jMenuSwitchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSwitchUserActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuSwitchUser);

        jMenuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuExit);

        jMenuBar2.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 0, 0));
        jMenu4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jMenu4.setText("      Manage Students    ");

        jMenuUpdateStudent.setText("Update Student");
        jMenuUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUpdateStudentActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuUpdateStudent);

        jMenuSearchStudent.setText("Search Student");
        jMenuSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchStudentActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuSearchStudent);

        jMenuDeleteStudent.setText("Delete Student");
        jMenuDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDeleteStudentActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuDeleteStudent);

        jMenuListStudents.setText("List Students");
        jMenuListStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListStudentsActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuListStudents);

        jMenuBar2.add(jMenu4);

        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu1.setText("       Manage Books      ");

        jMenuUpdateBook.setText("Update Book");
        jMenuUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUpdateBookActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuUpdateBook);

        jMenuSearchBook.setText("Search Book");
        jMenuSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSearchBookActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSearchBook);

        jMenuDeleteBook.setText("Delete Book");
        jMenuDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDeleteBookActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuDeleteBook);

        jMenuListBook.setText("List Books");
        jMenuListBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListBookActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuListBook);

        jMenuBar2.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jMenu2.setText("       Manage Library      ");

        jMenuUserAccount.setText("User Account");
        jMenuUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUserAccountActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuUserAccount);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        String sql="UPDATE ACCOUNT SET STATUS = FALSE WHERE STATUS = TRUE";
        try{
            conn.prepareStatement(sql).executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Close();
        System.exit(1);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUpdateStudentActionPerformed
        Close();
        UpdateStudent Us=new UpdateStudent();
        Us.setVisible(true);
    }//GEN-LAST:event_jMenuUpdateStudentActionPerformed

    private void jbtnTransactionHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTransactionHistoryActionPerformed
        Close();
        ViewTransaction VT=new ViewTransaction();
        VT.setVisible(true);
    }//GEN-LAST:event_jbtnTransactionHistoryActionPerformed

    private void jbtnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogoutActionPerformed
        String sql="UPDATE ACCOUNT SET STATUS = FALSE ";
        this.setVisible(false);
        try{
            conn.prepareStatement(sql).executeUpdate();
            Close();
            LoginPage l=new LoginPage();
            l.setVisible(true);
            JOptionPane.showMessageDialog(null,"Logged Out ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbtnLogoutActionPerformed

    private void jbtnNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewStudentActionPerformed
        Close();
        NewStudent N=new NewStudent();
        N.setVisible(true);
    }//GEN-LAST:event_jbtnNewStudentActionPerformed

    private void jbtnNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNewBookActionPerformed
        Close();
        NewBook nb=new NewBook();
        nb.setVisible(true);
    }//GEN-LAST:event_jbtnNewBookActionPerformed

    private void jbtnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchStudentActionPerformed
        // TODO add your handling code here:
        String sql="DELETE FROM PASSVALUE";
        try {
            conn.prepareStatement(sql).executeUpdate();
            sql="INSERT INTO PASSVALUE VALUES ('"+jtxtScholarNo.getText()+"')";
            pst=conn.prepareStatement(sql);
            pst.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
         try{
            sql="SELECT * FROM ROOT.STUDENT WHERE SCHOLARNO = '"+jtxtScholarNo.getText()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(null,"Student Not Found in Records");
            }
            else{
                Close();
                SearchStudent SB=new SearchStudent();
                SB.setVisible(true);
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Close();
    }//GEN-LAST:event_jbtnSearchStudentActionPerformed

    private void jtxtScholarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtScholarNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtScholarNoActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        clear();Close();
    }//GEN-LAST:event_jbtnClearActionPerformed
    private void jbtnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchBookActionPerformed
        String sql="DELETE FROM PASSVALUE";
        try{
            conn.prepareStatement(sql).executeUpdate();
            sql="INSERT INTO PASSVALUE VALUES ('"+jtxtISBN.getText()+"')";
            pst=conn.prepareStatement(sql);
            pst.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            sql="SELECT * FROM BOOK WHERE ISBN= '"+jtxtISBN.getText()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(null,"Book Not Found in Records");
            }
            else{
                Close();
                SearchBook SB=new SearchBook();
                SB.setVisible(true);
                return;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Close();
    }//GEN-LAST:event_jbtnSearchBookActionPerformed

    private void jbtnIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIssueBookActionPerformed
        //Student not in the records
        //Student cannot have more than 3 books issued at a time
        String ScholarNo=jtxtScholarNo.getText();
        String sql="SELECT * FROM STUDENT WHERE SCHOLARNO = '"+ScholarNo+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(!rs.next()){ JOptionPane.showMessageDialog(null,"Student not found in records");return ;}
            sql="SELECT * FROM STUDENT WHERE SCHOLARNO = '"+ScholarNo+"' AND BOOK1 IS NOT NULL AND BOOK3 IS NOT NULL AND BOOK2 IS NOT NULL";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){ JOptionPane.showMessageDialog(null,"Student already ISSUED 3 BOOKS");return ;}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        if(!checkMembership()){ JOptionPane.showMessageDialog(null,"Student's Membership Expired");return;}
        try{
            sql="DELETE FROM PASSVALUE";
            conn.prepareStatement(sql).executeUpdate();
            sql="INSERT INTO PASSVALUE VALUES ('"+ScholarNo+"')";
            conn.prepareStatement(sql).executeUpdate();
            Close();
            IssueBook IB=new IssueBook();
            IB.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbtnIssueBookActionPerformed

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
        String ISBN=jtxtISBN.getText();
        String sql="DELETE FROM ROOT.PASSVALUE";
        try{
            conn.prepareStatement(sql).executeUpdate();
            sql="INSERT INTO ROOT.PASSVALUE VALUES ('"+ISBN+"')";
            conn.prepareStatement(sql).executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        try{
            sql="SELECT * FROM BOOK WHERE ISBN = '"+ISBN+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(!rs.next()) {JOptionPane.showMessageDialog(null,"Book not in records");return;}
            else if(!Issued(ISBN)){JOptionPane.showMessageDialog(null,"Book not ISSUED");}
            else {
                Close();
                SubmitBook SB=new SubmitBook();
                SB.setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e+"Home Submit Button");
        }
    }//GEN-LAST:event_jbtnSubmitActionPerformed

    private void jMenuUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUpdateBookActionPerformed
        Close();
        UpdateBook Up=new UpdateBook();
        Up.setVisible(true);
    }//GEN-LAST:event_jMenuUpdateBookActionPerformed

    private void jMenuSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSearchStudentActionPerformed
        String UserName,sql;
        JTextField Text=new JTextField();
        Text.setText("");
        JPanel Panel=new JPanel(new GridLayout(0,1));
        Panel.add(new JLabel("Enter ScholarNo : "));
        Panel.add(Text);
        int result=JOptionPane.showConfirmDialog(null,Panel,"Search Student",JOptionPane.OK_CANCEL_OPTION);
        if(result==JOptionPane.OK_OPTION){
            UserName=Text.getText();
            sql="SELECT * FROM STUDENT WHERE SCHOLARNO = '"+UserName+"'";
            try{
                rs=conn.prepareStatement(sql).executeQuery();
                if(rs.next()){
                    sql="DELETE FROM PASSVALUE";
                    conn.prepareStatement(sql).executeUpdate();
                    conn.prepareStatement("INSERT INTO PASSVALUE VALUES ('"+UserName+"')").executeUpdate();
                    Close(); 
                    SearchStudent SS=new SearchStudent();
                     SS.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Student not in Records");
                    return ;
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
       
    }//GEN-LAST:event_jMenuSearchStudentActionPerformed

    private void jMenuSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSearchBookActionPerformed
        String ISBN,sql;
        JTextField Text=new JTextField();
        JPanel Panel=new JPanel(new GridLayout(0,1));
        Text.setText("");
        Panel.add(new JLabel("Book ISBN :"));
        Panel.add(Text);
        int result=JOptionPane.showConfirmDialog(null,Panel,"Search Book ",JOptionPane.OK_CANCEL_OPTION);
        if(result==JOptionPane.OK_OPTION){
            ISBN=Text.getText();
            sql="SELECT * FROM BOOK WHERE ISBN  = '"+ISBN+"'";
            try{
                if(conn.prepareStatement(sql).executeQuery().next()){
                    conn.prepareStatement("DELETE FROM PASSVALUE").executeUpdate();
                    conn.prepareStatement("INSERT INTO PASSVALUE VALUES ('"+ISBN+"')").executeUpdate();
                    Close();
                    SearchBook SB=new SearchBook();
                    SB.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null,"Book not in Records");
                    return;
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
        
    }//GEN-LAST:event_jMenuSearchBookActionPerformed

    private void jMenuSwitchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSwitchUserActionPerformed
        String sql="UPDATE ACCOUNT SET STATUS = FALSE WHERE STATUS = TRUE";
        try{
            conn.prepareStatement(sql).executeUpdate();
            Close();
            LoginPage Lp=new LoginPage();
            Lp.setVisible(true);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null,"Logged Out");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jMenuSwitchUserActionPerformed

    private void jMenuListStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListStudentsActionPerformed
        Close();
        ListStudent Lb=new ListStudent();
        Lb.setVisible(true);
    }//GEN-LAST:event_jMenuListStudentsActionPerformed

    private void jMenuListBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListBookActionPerformed
        Close();
        ListBook Lb=new ListBook();
        Lb.setVisible(true);
    }//GEN-LAST:event_jMenuListBookActionPerformed

    private void jMenuDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDeleteStudentActionPerformed
        Close();
        DeleteStudent DS=new DeleteStudent();
        DS.setVisible(true);
    }//GEN-LAST:event_jMenuDeleteStudentActionPerformed

    private void jMenuDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDeleteBookActionPerformed
        Close();
        DeleteBook DB=new DeleteBook();
        DB.setVisible(true);
    }//GEN-LAST:event_jMenuDeleteBookActionPerformed

    private void jMenuUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUserAccountActionPerformed
        Close();
        UserAccount UA=new UserAccount();
        UA.setVisible(true);
    }//GEN-LAST:event_jMenuUserAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuDeleteBook;
    private javax.swing.JMenuItem jMenuDeleteStudent;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuListBook;
    private javax.swing.JMenuItem jMenuListStudents;
    private javax.swing.JMenuItem jMenuSearchBook;
    private javax.swing.JMenuItem jMenuSearchStudent;
    private javax.swing.JMenuItem jMenuSwitchUser;
    private javax.swing.JMenuItem jMenuUpdateBook;
    private javax.swing.JMenuItem jMenuUpdateStudent;
    private javax.swing.JMenuItem jMenuUserAccount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnIssueBook;
    private javax.swing.JButton jbtnLogout;
    private javax.swing.JButton jbtnNewBook;
    private javax.swing.JButton jbtnNewStudent;
    private javax.swing.JButton jbtnSearchBook;
    private javax.swing.JButton jbtnSearchStudent;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JButton jbtnTransactionHistory;
    private javax.swing.JTextField jtxtISBN;
    private javax.swing.JTextField jtxtScholarNo;
    // End of variables declaration//GEN-END:variables
}
