/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.librarymanagement;
import java.sql.*;
import java.util.*;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Suraj Upadhyay
 */
public class NewStudent extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form NewStudent
     */
    public NewStudent() {
        super("New Student");
        initComponents();
        try{
            conn=DriverManager.getConnection(LoginPage.JDBC_URL,"Root","root");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtStudentFullName = new javax.swing.JTextField();
        jtxtGender = new javax.swing.JComboBox<>();
        jtxtBranch = new javax.swing.JComboBox<>();
        jtxtSemester = new javax.swing.JComboBox<>();
        jtxtDOB = new javax.swing.JTextField();
        jtxtStartDate = new javax.swing.JTextField();
        jtxtEndDate = new javax.swing.JTextField();
        jbtnCreateStudent = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jrdToday = new javax.swing.JRadioButton();
        jrdYear = new javax.swing.JRadioButton();
        jrdMonth = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jLabel11.setText("jLabel11");

        setTitle("New Student");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 204)), "New Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 204, 204))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Scholar No. :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Full Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Gender : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Branch :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Semester :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("DOB :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Membership :");

        jLabel8.setText("Start Date :");

        jLabel9.setText("End Date :");

        jtxtGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jtxtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGenderActionPerformed(evt);
            }
        });

        jtxtBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ECE", "IT" }));

        jtxtSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        jtxtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDOBActionPerformed(evt);
            }
        });

        jtxtEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEndDateActionPerformed(evt);
            }
        });

        jbtnCreateStudent.setText("Create Student");
        jbtnCreateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateStudentActionPerformed(evt);
            }
        });

        jbtnClear.setText("Clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnExit.setText("Back");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jrdToday.setText("Today");
        jrdToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdTodayActionPerformed(evt);
            }
        });

        jrdYear.setText("1 Year");
        jrdYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdYearActionPerformed(evt);
            }
        });

        jrdMonth.setText("6 Months");
        jrdMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdMonthActionPerformed(evt);
            }
        });

        jLabel10.setText("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnClear)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtxtStudentFullName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtStudentID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtnExit)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtxtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jtxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jrdYear)
                                .addComponent(jrdToday)
                                .addComponent(jrdMonth))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnCreateStudent)
                        .addGap(103, 103, 103)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtStudentFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrdToday))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jrdYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrdMonth))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCreateStudent)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnClear))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrdMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdMonthActionPerformed
        if(jrdMonth.isSelected()){
            jrdYear.setSelected(false);
            if(jtxtStartDate.getText().equals("")){JOptionPane.showMessageDialog(null,"Start Membership Field Empty"); return;}
            Calendar c=Calendar.getInstance();
            c.setTime(new java.util.Date());
            c.add(Calendar.MONTH,6);
            java.sql.Date End=new java.sql.Date(c.getTime().getTime());
            jtxtEndDate.setText(""+End);
        }else{
            jtxtEndDate.setText("");
        }
    }//GEN-LAST:event_jrdMonthActionPerformed

    private void jrdYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdYearActionPerformed
        if(jrdYear.isSelected()){
            jrdMonth.setSelected(false);
            if(jtxtStartDate.getText().equals("")){JOptionPane.showMessageDialog(null,"Start Membership Field Empty"); return;}
            Calendar c=Calendar.getInstance();
            c.setTime(new java.util.Date());
            c.add(Calendar.YEAR, 1);
            java.sql.Date End=new java.sql.Date(c.getTime().getTime());
            jtxtEndDate.setText(""+End);
        }
        else{
            jtxtEndDate.setText("");
        }
    }//GEN-LAST:event_jrdYearActionPerformed

    private void jrdTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdTodayActionPerformed
        if(jrdToday.isSelected()){
            java.sql.Date Today=new java.sql.Date(new java.util.Date().getTime());
            jtxtStartDate.setText(""+Today);
        }
        else{
            jtxtStartDate.setText("");
        }
    }//GEN-LAST:event_jrdTodayActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        jtxtStudentID.setText("");
        jtxtStudentFullName.setText("");
        jtxtDOB.setText("");
        jtxtStartDate.setText("");
        jtxtEndDate.setText("");
        jrdToday.setSelected(false);
        jrdYear.setSelected(false);
        jrdMonth.setSelected(false);
        this.setVisible(false);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        // TODO add your handling code here:
        jtxtStudentID.setText("");
        jtxtStudentFullName.setText("");
        jtxtDOB.setText("");
        jtxtStartDate.setText("");
        jtxtEndDate.setText("");
        jrdToday.setSelected(false);
        jrdYear.setSelected(false);
        jrdMonth.setSelected(false);
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnCreateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateStudentActionPerformed
        // TODO add your handling code here:
        //StudentID here stores value for Student's Scholar No.
        String StudentID=jtxtStudentID.getText();
        String FullName=jtxtStudentFullName.getText();
        String Gender=jtxtGender.getSelectedItem().toString();
        String Branch=jtxtBranch.getSelectedItem().toString();
        int Semester=Integer.parseInt(jtxtSemester.getSelectedItem().toString());
        if(StudentID.length()!=8){ JOptionPane.showMessageDialog(null,"ScholarNo must be like YEAR+U/P+BRANCHCODE+3-DIGIT ROLLNO");return ;}
        java.sql.Date DOB;
        java.sql.Date StartDate;
        java.sql.Date EndDate;
        if(StudentID.equals("")||FullName.equals("")||jtxtDOB.getText().equals("")||jtxtStartDate.getText().equals("")
                ||jtxtEndDate.getText().equals(""))
                            {JOptionPane.showMessageDialog(null,"Required Fields are Empty");return ;}
        try{
            java.util.Date utilDate=new SimpleDateFormat("yyyy-MM-dd").parse( jtxtDOB.getText());
            DOB=new java.sql.Date(utilDate.getTime());
            utilDate=new SimpleDateFormat("yyyy-MM-dd").parse(jtxtStartDate.getText());
            StartDate=new java.sql.Date(utilDate.getTime());
            utilDate=new SimpleDateFormat("yyyy-MM-dd").parse(jtxtEndDate.getText());
            EndDate=new java.sql.Date(utilDate.getTime());
            String sql="INSERT INTO ROOT.STUDENT (SCHOLARNO,STUDENTNAME,GENDER,BRANCH,SEMESTER,DOB,MEM_START,MEM_END)"
            + " VALUES ('"+StudentID+"','"+FullName+"','"+Gender+"',"
            + "'"+Branch+"',"+Semester+",'"+DOB+"','"+StartDate+"','"+EndDate+"')";
            pst=conn.prepareStatement(sql);
            pst.executeUpdate();
            jtxtStudentID.setText("");
            jtxtStudentFullName.setText("");
            jtxtDOB.setText("");
            jtxtStartDate.setText("");
            jtxtEndDate.setText("");
            jrdToday.setSelected(false);
            jrdYear.setSelected(false);
            jrdMonth.setSelected(false);
            JOptionPane.showMessageDialog(null,"Student entry made in database");
        }catch(ParseException P){
            JOptionPane.showMessageDialog(null,P);
        } catch (SQLException ex) {
            Logger.getLogger(NewStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbtnCreateStudentActionPerformed

    private void jtxtEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEndDateActionPerformed

    private void jtxtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGenderActionPerformed

    private void jtxtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDOBActionPerformed
    }//GEN-LAST:event_jtxtDOBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           Class.forName(LoginPage.DRIVER);
           
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnCreateStudent;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JRadioButton jrdMonth;
    private javax.swing.JRadioButton jrdToday;
    private javax.swing.JRadioButton jrdYear;
    private javax.swing.JComboBox<String> jtxtBranch;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JTextField jtxtEndDate;
    private javax.swing.JComboBox<String> jtxtGender;
    private javax.swing.JComboBox<String> jtxtSemester;
    private javax.swing.JTextField jtxtStartDate;
    private javax.swing.JTextField jtxtStudentFullName;
    private javax.swing.JTextField jtxtStudentID;
    // End of variables declaration//GEN-END:variables
}
