/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.librarymanagement;
import java.awt.GridLayout;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Suraj Upadhyay
 */
public class UpdateStudent extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
String ScholarNo;
    /**
     * Creates new form UpdateStudent
     */
    public UpdateStudent() {
        super("Update Student");
        initComponents();
        try{
            Class.forName(LoginPage.DRIVER);
            conn=DriverManager.getConnection(LoginPage.JDBC_URL,"Root","root");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    int Login(){
        String UserName="";
        String Password="";
        String sql="SELECT * FROM ACCOUNT WHERE STATUS = TRUE";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){ UserName=rs.getString(1);Password=rs.getString(2);}
            else {JOptionPane.showMessageDialog(null,"Account Logged in Not recognized");return 0;}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            return 0;
        }
        JTextField text=new JTextField(10);
        JPasswordField Pswd=new JPasswordField(20);
        text.setText(UserName);
        text.setEditable(false);
        Pswd.setText("");
        JPanel panel = new JPanel(new GridLayout(0,2));
        panel.add(new JLabel("UserName : "));
        panel.add(text);
        panel.add(new JLabel("Password : "));
        panel.add(Pswd);
        int result=JOptionPane.showConfirmDialog(null,panel,"Confimation",JOptionPane.OK_CANCEL_OPTION);
        if(result==JOptionPane.OK_OPTION){
            if(Password.equals(String.valueOf(Pswd.getPassword()))) 
                {JOptionPane.showMessageDialog(null,"Are you SURE you want to SAVE THE CHANGES");
                    return 1;}
            else {
                JOptionPane.showMessageDialog(null,"Wrong Password ");
                return 0;
            }
        }
        else return 0;
    }
    int UpdateStudentBase(){
        String ScholarNo1=jtxtScholarNo.getText();
        String Name=jtxtStudentName.getText();
        String Branch=String.valueOf(jcomboBranch.getSelectedItem());
        String Semester=jtxtSem.getText();
        try {
            java.sql.Date DOB= new  java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(jtxtDOB.getText()).getTime());
            java.sql.Date Start=new  java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(jtxtStart.getText()).getTime());
            java.sql.Date End=new  java.sql.Date(new SimpleDateFormat("yyyy-MM-dd").parse(jtxtEnd.getText()).getTime());
            String sql="UPDATE STUDENT SET SCHOLARNO = '"+ScholarNo1+"' ,STUDENTNAME = '"+Name+"' ,"
                    + " BRANCH = '"+Branch+"' , SEMESTER = "+Semester+" , DOB = '"+DOB+"' ,"
                    + " MEM_START = '"+Start+"' , MEM_END = '"+End+"' WHERE SCHOLARNO = '"+ScholarNo+"'";
            conn.prepareStatement(sql).executeUpdate();
            sql="UPDATE BOOK SET SCHOLARNO = '"+ScholarNo1+"' WHERE SCHOLARNO = '"+ScholarNo+"'";
            conn.prepareStatement(sql).executeUpdate();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,ex);
            return 0;
        }
        ScholarNo=ScholarNo1;
        return 1;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtStart = new javax.swing.JTextField();
        jtxtEnd = new javax.swing.JTextField();
        jtxtBook1 = new javax.swing.JTextField();
        jtxtBook2 = new javax.swing.JTextField();
        jtxtBook3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxtDOB = new javax.swing.JTextField();
        jtxtSem = new javax.swing.JTextField();
        jbtnSemIncrease = new javax.swing.JButton();
        jbtnSemDecrease = new javax.swing.JButton();
        jcomboBranch = new javax.swing.JComboBox<>();
        jtxtGender = new javax.swing.JTextField();
        jtxtStudentName = new javax.swing.JTextField();
        jtxtScholarNo = new javax.swing.JTextField();
        jbtnUpdate = new javax.swing.JButton();
        jbtnSearch = new javax.swing.JButton();

        setTitle("Update Student");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 204), 2, true), "Update Student", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 0, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Scholar No : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Student Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Branch :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Semester :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Date Of Birth :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Membership :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Books Issued :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Gender :");

        jLabel3.setText("From");

        jLabel10.setText("To");

        jtxtBook1.setEditable(false);

        jtxtBook2.setEditable(false);

        jtxtBook3.setEditable(false);

        jLabel11.setText("1 :");

        jLabel12.setText("2 :");

        jLabel13.setText("3 :");

        jtxtSem.setEditable(false);

        jbtnSemIncrease.setText("+");
        jbtnSemIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSemIncreaseActionPerformed(evt);
            }
        });

        jbtnSemDecrease.setText("-");
        jbtnSemDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSemDecreaseActionPerformed(evt);
            }
        });

        jcomboBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ECE", "IT" }));

        jtxtGender.setEditable(false);

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtxtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jtxtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbtnUpdate)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jtxtBook2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel13)))))
                                .addGap(18, 18, 18)
                                .addComponent(jtxtBook3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtSem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtnSemIncrease)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtnSemDecrease))
                                    .addComponent(jcomboBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtStudentName)
                                    .addComponent(jtxtScholarNo, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnSearch))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtScholarNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSearch))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jtxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcomboBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSemIncrease)
                    .addComponent(jbtnSemDecrease))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtBook2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jtxtBook3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(jbtnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        ScholarNo=jtxtScholarNo.getText();
        String sql="SELECT * FROM STUDENT WHERE SCHOLARNO = '"+ScholarNo+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                jtxtStudentName.setText(rs.getString(2));
                jtxtGender.setText(rs.getString(11));
                jcomboBranch.setSelectedItem(rs.getString(3));
                jtxtSem.setText(rs.getString(4));
                jtxtDOB.setText(rs.getString(5));
                jtxtStart.setText(rs.getString(6));
                jtxtEnd.setText(rs.getString(7));
                jtxtBook1.setText(rs.getString(8));
                jtxtBook2.setText(rs.getString(9));
                jtxtBook3.setText(rs.getString(10));
            }
            else{
                JOptionPane.showMessageDialog(null,"Student not found in Records");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        //Check for Password
        //Update Student Database
        //Update Book Database if any Issued
        if(Login()==0) {JOptionPane.showMessageDialog(null,"Cannot Update : Some Error Occured"); return;}
        if(UpdateStudentBase()==0) {JOptionPane.showMessageDialog(null,"Cannot Update : Some Error Occured"); return;}
        JOptionPane.showMessageDialog(null,"Student Updated Successfully");
        try{
            rs.close();
            pst.close();
            conn.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnSemIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSemIncreaseActionPerformed
        int Semester=Integer.parseInt(jtxtSem.getText());
        if(Semester==8) {JOptionPane.showMessageDialog(null,"Semester Cannot be Increased Further");return ;}
        Semester++;
        jtxtSem.setText(""+Semester);
    }//GEN-LAST:event_jbtnSemIncreaseActionPerformed

    private void jbtnSemDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSemDecreaseActionPerformed
        int Semester=Integer.parseInt(jtxtSem.getText());
        if(Semester==1) {JOptionPane.showMessageDialog(null,"Semester Cannot be Decreased Further");return ;}
        Semester--;
        jtxtSem.setText(""+Semester);
    }//GEN-LAST:event_jbtnSemDecreaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JButton jbtnSemDecrease;
    private javax.swing.JButton jbtnSemIncrease;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcomboBranch;
    private javax.swing.JTextField jtxtBook1;
    private javax.swing.JTextField jtxtBook2;
    private javax.swing.JTextField jtxtBook3;
    private javax.swing.JTextField jtxtDOB;
    private javax.swing.JTextField jtxtEnd;
    private javax.swing.JTextField jtxtGender;
    private javax.swing.JTextField jtxtScholarNo;
    private javax.swing.JTextField jtxtSem;
    private javax.swing.JTextField jtxtStart;
    private javax.swing.JTextField jtxtStudentName;
    // End of variables declaration//GEN-END:variables
}
